### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [83]:
import numpy as np

In [59]:
data = np.array(['강아지', '원숭이', '꽃', '45', '100']) # 자체가 리스트 객체이지만 45,100은 대표로 스트링객체가 나옴 
data.ndim #차원
len(data) #전체 갯수 => data.size 도 됨 
data.dtype #데이터형
data.shape #전체 구조
print(data.ndim, data.size ,data.dtype, data.shape)

1 5 <U3 (5,)


#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
# ones는 값을 유지하기 위해 데이터 초기화를 해주는 것 => ones가 아직 난해하다...ㅠㅠ
np.ones((2,3)) 

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [75]:
a= np.arange(51,81).reshape(-1,5)
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
a

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

In [81]:
a= np.arange(51,81)
a.reshape(6,5)

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [84]:
result = a.astype(float)
result.dtype

dtype('float64')

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [112]:
# 배열을 1차원으로 펼치기 (행 크기 자동 조절) : a.shape = -1
a = np.array([[ 1,  4,  5,  6],[56, 23, 45, 67], [ 8,  4,  6, 10]])
a.shape = -1 
a[5:-1]

array([23, 45, 67,  8,  4,  6])

In [111]:
#flatten 함수 사용하기
a = np.array([[ 1,  4,  5,  6],[56, 23, 45, 67], [ 8,  4,  6, 10]])
a.flatten()[5:-1]

array([23, 45, 67,  8,  4,  6])

In [106]:
# 배열을 3차원으로 변환 연습 (행은 1, 열은 3, 깊이는 자동으로 조정) 
a = np.array([[ 1,  4,  5,  6],[56, 23, 45, 67], [ 8,  4,  6, 10]])
a.shape = 1,3, -1
a

array([[[ 1,  4,  5,  6],
        [56, 23, 45, 67],
        [ 8,  4,  6, 10]]])

#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [117]:
a= np.arange(1,11)
a[[0,7,8,9]]=[10,0,0,0]
a

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

In [118]:
a= np.arange(1,11)
a[0]=10
a[7:] = 0
a

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [122]:
np.random.randint(10, 99, 25).reshape(5,5)

np.random.randint(10, 99, (5,5))

array([[48, 19, 89, 43, 95],
       [97, 83, 49, 35, 43],
       [21, 53, 77, 46, 55],
       [73, 22, 76, 25, 86],
       [96, 33, 87, 78, 44]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [126]:
a=np.random.randint(1, 101, 7)
print(a, a.max(), a.min())
np.max(a), np.min(a)

[78 79 87 65 22  2 19] 87 2


(87, 2)

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [148]:
# 3개의 넘파이 배열을 생성하는 방법 
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(11, 20).reshape(3, 3)
arr3 = np.arange(21, 30).reshape(3, 3)
arr1,arr2,arr3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

**배열 합치기**   
np.vstack((배열1,배열2....)) : 세로 합치기   
np.hstack((배열1,배열2....)) : 가로 합치기   
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [149]:
b= np.hstack((arr1,arr2,arr3)) #가로로 쭉 이어붙이기
b, b.ndim, b.shape

(array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
        [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
        [ 7,  8,  9, 17, 18, 19, 27, 28, 29]]),
 2,
 (3, 9))

In [150]:
np.concatenate((arr1,arr2,arr3),axis=1) #concatenate도 가능!! 

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [152]:
b= np.vstack((arr1,arr2,arr3)) #세로로 쭉 이어붙이기
b, b.ndim, b.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]),
 2,
 (9, 3))

In [153]:
np.concatenate((arr1,arr2,arr3),axis=0) #concatenate도 가능!! 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [133]:
# 3개의 넘파이 배열을 로그로 생성하는 또다른 방법 
arr1 = np.linspace(1, 9, 9).reshape(3, 3)
arr2 = np.linspace(11, 19, 9).reshape(3, 3)
arr3 = np.linspace(21, 29, 9).reshape(3, 3)
arr1,arr2,arr3

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]]),
 array([[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]))

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [161]:
# 중복 없이, 100까지 숫자 중 40개를 추출 가능 (비복원 추출- 한 번 뽑은 걸 다시 넣지 않음), randint는 중복 생김 
arr = np.random.choice(100, 40, replace=False)
arr, arr[arr>50] # 50보다 큰 숫자만 필터링

(array([88, 81, 35, 50, 13, 43, 12, 42, 64, 44, 99,  3, 32,  5, 25, 93, 22,
        65, 33, 63,  0,  4, 36, 18, 20, 47, 97, 24, 67, 11, 78, 77, 94, 15,
        55, 74, 80, 52, 57, 79]),
 array([88, 81, 64, 99, 93, 65, 63, 97, 67, 78, 77, 94, 55, 74, 80, 52, 57,
        79]))

In [162]:
#where 조건만 넣어줬을 때는 인덱스만 반환함
arr[np.where(arr>50)]

array([88, 81, 64, 99, 93, 65, 63, 97, 67, 78, 77, 94, 55, 74, 80, 52, 57,
       79])

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [173]:
kor = np.array( [60,55,70,30,20,90])

In [164]:
max(kor)
kor.max()

90

In [73]:
kor[(kor>=80)]

array([90])

In [74]:
# 3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
kor[(kor>=50)&(kor<=80)]

array([60, 55, 70])

In [170]:
# 4. 국어점수의 평균을 구하여라
kor.mean(), round(np.mean(kor),2)

(54.166666666666664, 54.17)

In [172]:
# 5. 국어점수의 총합을 구하여라.
kor.sum()
np.sum(kor)

325

In [175]:
# 6. 국어점수가 40점이하인 데이터를 삭제하여라
import copy
kor1 = kor.copy()
kor1, np.delete(kor1, np.where(kor1<40))

(array([60, 55, 70, 30, 20, 90]), array([60, 55, 70, 90]))

In [181]:
#7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
np.where(kor>=50,kor*1.1,kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [188]:
# 8. 국어점수 top 3를 구하여라 (arg소팅!!)
kor[np.argsort(kor)[::-1]][:3]
np.sort(kor)[::-1][:3]

array([90, 70, 60])

In [182]:
# 9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요
np.where(kor>=70,'합격','불합격')

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

### 멘토님 문제

In [189]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
              4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print('갯수 :',len(x))
print('합계 :',np.sum(x))
print('평균 :',np.mean(x), np.average(x))
print('분산 :',np.var(x))
print('표준편차 :',np.std(x))
print('최대 :',np.max(x))
print('최소 :',np.min(x))
print('중앙값 :',np.median(x))

갯수 : 26
합계 : 125
평균 : 4.8076923076923075 4.8076923076923075
분산 : 115.23224852071006
표준편차 : 10.734628476137871
최대 : 23
최소 : -24
중앙값 : 5.0


In [190]:
import numpy as np
ar = np.arange(10).reshape(2,5)
print(ar)
print(ar.T) # 행과 열을 변경
print(ar.transpose()) # 행과 열을 변경

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [196]:
# br 0~19 4행 5열 -> 행과 열을 교환
br = np.arange(20).reshape(4, 5)
print(br)
print(br.T)
print(br.reshape(5,4))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [237]:
import pandas as pd
from pandas import Series, DataFrame
items = {'1':{'name':'apple', 'manufacture':'korea', 'price':1500},
'2': {'name': 'watermelon', 'manufacture': 'korea', 'price': 15000},
'3': {'name':'oriental melon','manufacture': 'korea','price': 1000},
'4': {'name': 'banana', 'manufacture': 'philippines', 'price': 500},
'5': {'name': 'lemon', 'manufacture': 'korea', 'price': 1500},
'6': {'name': 'mango', 'manufacture': 'korea', 'price': 700}}
data = DataFrame(items)
data

1           2               3            4      5      6
name         apple  watermelon  oriental melon       banana  lemon  mango
manufacture  korea       korea           korea  philippines  korea  korea
price         1500       15000            1000          500   1500    700

In [239]:
data[['1']]

1
name         apple
manufacture  korea
price         1500

In [240]:
data[['1','3']]

1               3
name         apple  oriental melon
manufacture  korea           korea
price         1500            1000

In [241]:
data[:1]

1           2               3       4      5      6
name  apple  watermelon  oriental melon  banana  lemon  mango

In [242]:
data[1:3]

1      2      3            4      5      6
manufacture  korea  korea  korea  philippines  korea  korea
price         1500  15000   1000          500   1500    700

In [244]:
data = data.T   #  행과 열을 변경
print(data)

             name  manufacture  price
1           apple        korea   1500
2      watermelon        korea  15000
3  oriental melon        korea   1000
4          banana  philippines    500
5           lemon        korea   1500
6           mango        korea    700


In [245]:
# 컬럼명이 price중에서 값이 10001보다 큰 데이터
result = data[data['price'] > 10001]
result

name manufacture  price
2  watermelon       korea  15000

In [246]:
# True데이터 만 출력
data.iloc[0] #integer location 정수 기반의 인덱싱, 1째 행만 반환 

name           apple
manufacture    korea
price           1500
Name: 1, dtype: object

In [247]:
data.loc[:'1','name']

1    apple
Name: name, dtype: object

In [248]:
data.loc['1':'2',['name','price']]

name  price
1       apple   1500
2  watermelon  15000

In [249]:
data.loc[:'3',['name','price']]   # 문자일 때는 포함

name  price
1           apple   1500
2      watermelon  15000
3  oriental melon   1000

In [250]:
data.loc[data.price>1000,['name','price']]

name  price
1       apple   1500
2  watermelon  15000
5       lemon   1500